use bumpalo::boxed::Box;
use num_bigint::BigInt;
use regress::Regex;
use yavashark_string::YSString;

pub enum Expression<'alloc> {
    BooleanLit(bool),
    NullLit,
    FloatLit(f64),
    Int32Lit(i32),
    StringLit(YSString),
    BigIntLit(Box<'alloc, BigInt>),
    RegExpLit(Box<'alloc, Regex>),
    TemplateLit(Box<'alloc, TemplateLiteral<'alloc>>),
    Ident(YSString),
    MetaProp(Box<'alloc, MetaProp>),
    Super(Box<'alloc, SuperProp>),
    ArrayLit(Box<'alloc, ArrayLiteral<'alloc>>),
    ArrowFunction(Box<'alloc, ArrowFunction<'alloc>>),
    Assignment(Box<'alloc, AssignmentExpression<'alloc>>),
    Await(Box<'alloc, AwaitExpression<'alloc>>),
    Binary(Box<'alloc, BinaryExpression<'alloc>>),
    Call(Box<'alloc, CallExpression<'alloc>>),
    Chain(Box<'alloc, ChainExpression<'alloc>>),
    Class(Box<'alloc, ClassExpression<'alloc>>),
    Conditional(Box<'alloc, ConditionalExpression<'alloc>>),
    Function(Box<'alloc, FunctionExpression<'alloc>>),
    Import(Box<'alloc, ImportExpression<'alloc>>),
    Logical(Box<'alloc, LogicalExpression<'alloc>>),
    New(Box<'alloc, NewExpression<'alloc>>),
    Object(Box<'alloc, ObjectExpression<'alloc>>),
    Sequence(Box<'alloc, SequenceExpression<'alloc>>),
    TaggedTemplate(Box<'alloc, TaggedTemplateExpression<'alloc>>),
    This,
    Unary(Box<'alloc, UnaryExpression<'alloc>>),
    Update(Box<'alloc, UpdateExpression<'alloc>>),
    Yield(Box<'alloc, YieldExpression<'alloc>>),
    PrivateIn(Box<'alloc, PrivateInExpression<'alloc>>),
    Member(Box<'alloc, MemberExpression<'alloc>>),
    ComputedMember(Box<'alloc, ComputedMemberExpression<'alloc>>),
    PrivateField(Box<'alloc, PrivateFieldExpression<'alloc>>),
}
