[package]
name = "yavashark_bytecode"
version = "0.1.0"
edition = "2021"

[dependencies]
yavashark_value = { path = "../yavashark_value" }
bincode = "2.0.0-rc.3"
num-bigint = "0.4.6"
swc_ecma_ast = "6.1.0"

[lints]
workspace = true
