[package]
name = "yavashark_bytecode"
version = "0.1.0"
edition = "2021"

[dependencies]
yavashark_string = { path = "../yavashark_string" }
bincode = "2.0.0-rc.3"
num-bigint = "0.4.6"
swc_ecma_ast = "17.0.0"


[features]
default = []
simple_bytecode = []

[lints]
workspace = true
