[package]
name = "yavashark_parser"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.81"
yavashark_lexer = { path = "../yavashark_lexer" }
slotmap = "1.0.7"
