[package]
name = "yavashark_compiler"
version = "0.1.0"
edition = "2024"

[dependencies]
yavashark_bytecode = { path = "../yavashark_bytecode" }
swc_ecma_ast = "15.0.0"
anyhow = "1.0.86"
log = "0.4.22"
num-traits = "0.2.19"

[lints]
workspace = true
