[package]
name = "yavashark_bytecode_interpreter"
version = "0.1.0"
edition = "2024"

[dependencies]
yavashark_env = { path = "../yavashark_env", default-features = false }
yavashark_vm = { path = "../yavashark_vm", default-features = false }
yavashark_codegen = { path = "../yavashark_codegen" }
yavashark_compiler = { path = "../yavashark_compiler" }
yavashark_bytecode = { path = "../yavashark_bytecode" }
swc_ecma_ast = "29.0.0"



[features]
default = ["temporal", "icu", "annex_b"]
temporal = ["yavashark_env/temporal"]
icu = ["yavashark_env/icu"]
annex_b = ["yavashark_env/annex_b"]

[lints]
workspace = true
