[package]
name = "yavashark_garbage"
version = "0.1.0"
edition = "2021"
description = "A garbage collector for the YavaShark JS/TS engine... Maybe it should collect js completely?"

[dependencies]
log = "0.4.21"
rand = "0.9.0-alpha.1"
bitflags = "2.5.0"

[lints]
workspace = true


[dev-dependencies]
env_logger = "0.11.3"



