[package]
name = "yavashark_env"
version = "0.1.0"
edition = "2021"

[dependencies]
yavashark_value = { path = "../yavashark_value", features = ["js", "dbg_object_gc" , "display_object"], default-features = false }
yavashark_garbage = { path = "../yavashark_garbage" }
yavashark_macro = { path = "../yavashark_macro" }
colored = "2.1.0"
paste = "1.0.15"
rand = "0.8.5"
num-bigint = "0.4.6"
regex = "1.11.1"


[features]
default = []
tests = []
out-of-spec-experiments = []

[lints]
workspace = true
