name: PR Test262 CI

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-test262:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Checkout test262 repository
        uses: actions/checkout@v4
        with:
          repository: tc39/test262
          path: test262

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Build Go Runner
        working-directory: crates/yavashark_test262/runner
        run: |
          go build

      - name: Build engine
        working-directory: crates/yavashark_test262
        run: |
          cargo build --release

      - name: Checkout data repository
        uses: actions/checkout@v3
        with:
          repository: Sharktheone/yavashark-data
          fetch-depth: '1'
          path: data

      - name: Run Test262 Runner
        working-directory: crates/yavashark_test262
        run: |
          ./runner/yavashark_test262_runner --ci --repo ../../data --test_root ../../test262/test --workers 256
